on:
  pull_request:
    types:
      - closed

jobs:
  delete-branch:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete merged branch
        env:
          GH_TOKEN: ${{ github.token }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: gh api --method DELETE "repos/${{ github.repository }}/git/refs/heads/$BRANCH"
